# Generated by Django 5.0.3 on 2024-03-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0003_alter_tag_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
