# Generated by Django 5.0.3 on 2024-03-28 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0005_tag_user_tag_tag_of_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quote",
            old_name="author",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="quote",
        ),
    ]
