# Generated by Django 5.0.3 on 2024-03-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0006_rename_author_quote_user_remove_quote_quote"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="quote",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
