# Generated by Django 5.0.3 on 2024-03-29 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0007_quote_quote"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tag",
            name="tag of username",
        ),
        migrations.RenameField(
            model_name="quote",
            old_name="user",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="user",
            new_name="author",
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("author", "name"), name="tag of username"
            ),
        ),
    ]
