# Generated by Django 5.0.3 on 2024-03-31 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0008_remove_tag_tag_of_username_rename_user_quote_author_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tag",
            name="tag of username",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="author",
        ),
    ]
