# Generated by Django 5.0.3 on 2024-03-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0009_remove_tag_tag_of_username_remove_tag_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("name",), name="tag of username"
            ),
        ),
    ]
