# Generated by Django 5.0.3 on 2024-04-01 18:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0016_alter_tag_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="user",
        ),
    ]
