# Generated by Django 5.0.3 on 2024-04-01 18:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0017_remove_author_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="author",
        ),
    ]
